const { dependencies, endpoints, environment, expressions, imports, schema } = program;

program.name = 'github';

environment
  .add('ACCESS_TOKEN', 'An access token')

endpoints
  .https('webhook', 'A webhook endpoint to receive notifications from Github')

expressions
  .add('url', '^https?://github.com/.+$')
  .add('repo', '^[a-zA-Z0-9-]+/[a-zA-Z0-9-_]+$')

schema.type('Root')
  .field('users', 'UserCollection')

schema.type('UserCollection')
  .computed('one', 'User')
    .param('name', 'String')
  .computed('page', 'UserPage')
    .param('since', 'Int')

schema.type('UserPage')
  .field('items', '[User]')
  .field('next', 'UserPage*')

schema.type('User')
  .computed('self', 'User*')
  .computed('avatarUrl', 'String')
  .computed('createdAt', 'String')
  .computed('gravatarId', 'String')
  .computed('publicGists', 'Int')
  .computed('publicRepos', 'Int')
  .computed('repos', 'RepositoryCollection')
  .computed('siteAdmin', 'Boolean')
  .computed('updatedAt', 'String')
  .field('bio', 'String')
  .field('blog', 'String')
  .field('company', 'String')
  .field('email', 'String')
  .field('followers', 'Int')
  .field('following', 'Int')
  .field('hireable', 'Boolean')
  .field('id', 'Int')
  .field('location', 'String')
  .field('login', 'String')
  .field('name', 'String')
  .field('type', 'String')

schema.type('RepositoryCollection')
  .computed('one', 'Repository')
    .param('name', 'String')
  .computed('page', 'RepositoryPage')
    .param('type', 'String')
    .param('sort', 'String')
    .param('direction', 'String')
    .param('page', 'Int')
    .param('pageSize', 'Int')

schema.type('RepositoryPage')
  .field('items', '[Repository]')
  .field('next', 'RepositoryPage*')

schema.type('Repository')
  .computed('self', 'Repository*')
  .computed('allowMergeCommit', 'String')
  .computed('allowRebaseMerge', 'String')
  .computed('allowSquashMerge', 'String')
  .computed('createdAt', 'String')
  .computed('defaultBranch', 'String')
  .computed('forksCount', 'Int')
  .computed('fullName', 'String')
  .computed('hasDownloads', 'Boolean')
  .computed('hasIssues', 'Boolean')
  .computed('hasPages', 'Boolean')
  .computed('hasWiki', 'Boolean')
  .computed('htmlUrl', 'String')
  .computed('issues', 'IssueCollection')
  .computed('networkCount', 'Int')
  .computed('openIssuesCount', 'Int')
  .computed('pushedAt', 'String')
  .computed('stargazersCount', 'Int')
  .computed('subscribersCount', 'Int')
  .computed('updatedAt', 'String')
  .computed('watchersCount', 'Int')
  .field('archived', 'String')
  .field('description', 'String')
  .field('fork', 'Boolean')
  .field('homepage', 'String')
  .field('id', 'Int')
  .field('language', 'String')
  .field('name', 'String')
  .field('private', 'Boolean')
  .field('size', 'String')
  .field('url', 'String')

schema.type('IssueCollection')
  .computed('one', 'Issue')
    .param('number', 'Int')
  .computed('page', 'IssuePage')
    .param('filter', 'String') // TODO: shold be enum
    .param('state', 'String')
    .param('labels', 'String')
    .param('sort', 'String')
    .param('direction', 'String')
    .param('since', 'String')
    .param('page', 'Int')
    .param('pageSize', 'Int')

schema.type('IssuePage')
  .field('items', '[Issue]')
  .field('next', 'IssuePage*')

schema.type('Issue')
  .computed('self', 'Issue*')
  .field('number', 'Int')
  .field('title', 'String')
  .field('id', 'Int')
  .field('state', 'String')
  .field('body', 'String')
  .field('locked', 'Boolean')
  .computed('activeLockReason', 'String')
  .field('comments', 'Int')
